### ISSUE TITLE
Got an Log Warning on server with Hugh Modpack

### ISSUE THREAD

**Issue by suerion** [Unknowneth/Mob-AI-Tweaks#14]
Latest Mob AI Tweaks
Fabric 1.21.1 on 0.16.7
Windows 11

In compat trying to fix issues with Async
https://github.com/AxalotLDev/Async/issues/1
```
[22:29:53] [Async-Tick-Pool-Thread-12/WARN]: A mod is trying to add an entity from offthread, this should be avoided. Printing trace:
java.lang.Exception: null
	at knot//MC/net.minecraft.server.world.ServerWorld.handler$bpa000$cupboard$OnaddEntity(MixinServerLevel.java:1786) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.server.world.ServerWorld.addEntity(MixinServerLevel.java) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.server.world.ServerWorld.spawnEntity(MixinServerLevel.java:893) ~[server-intermediary.jar:?]
	at knot/com.notunanancyowen.goals.HostileMobRandomlySitDownGoal.start(HostileMobRandomlySitDownGoal.java:64) ~[mob-ai-tweaks-1.3.6-1.21.jar:?]
	at knot//MC/net.minecraft.entity.ai.goal.PrioritizedGoal.start(PrioritizedGoal.java:41) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.entity.ai.goal.GoalSelector.tick(GoalSelector.java:99) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.entity.mob.MobEntity.tickNewAi(MobEntity.java:794) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.entity.LivingEntity.tickMovement(LivingEntity.java:2778) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity.java:572) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.entity.mob.HostileEntity.tickMovement(HostileEntity.java:44) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.entity.mob.ZombieEntity.tickMovement(ZombieEntity.java:266) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.entity.LivingEntity.tick(LivingEntity.java:2507) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.entity.mob.MobEntity.tick(MobEntity.java:372) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.entity.mob.ZombieEntity.tick(ZombieEntity.java:238) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.server.world.ServerWorld.mixinextras$bridge$method_5773$308(MixinServerLevel.java) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.server.world.ServerWorld.wrapOperation$gac001$porting_lib_entity$preEntityTick(MixinServerLevel.java:21807) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.server.world.ServerWorld.mixinextras$bridge$wrapOperation$gac001$porting_lib_entity$preEntityTick$309(MixinServerLevel.java) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.server.world.ServerWorld.wrapOperation$gep000$puzzleslib$tickNonPassenger(MixinServerLevel.java:23797) ~[server-intermediary.jar:?]
	at knot//MC/net.minecraft.server.world.ServerWorld.tickEntity(MixinServerLevel.java:770) ~[server-intermediary.jar:?]
	at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$3(ParallelProcessor.java:126) ~[async-0.1.0+rc5-1.21.1.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]

```

**Comment by suerion** [comment]
hey, got now an ne issue? 

![image](https://github.com/user-attachments/assets/e55c98fa-3e8d-424d-a71e-129b415ec058)


Here the Log
https://mclo.gs/xAe77Yb
on Line 7224

**Comment by Unknowneth** [comment]
My suggestion for now is to disable "hostile_mobs_randomly_sit_down" in the config till I find a fix for this

No clue when update will come out, very busy rn but will try to fix this

**Comment by suerion** [comment]
@Unknowneth thanks for answering, the workaround had worked

had a new issue here, will add this also in compat for ASYNC. If i got another issues, i will come here and add it in this issue

workaround: MOB Ai: villagers_have_special_roles=false
```
[19:59:12 WARN] [Async-Tick-Pool-Thread-12]: [Cupboard] A mod is trying to add an entity from offthread, this should be avoided. Printing trace:
java.lang.Exception: null
        at knot/net.minecraft.server.level.ServerLevel.handler$cid000$cupboard$OnaddEntity(MixinServerLevel.java:1786) ~[?:?]
        at knot/net.minecraft.server.level.ServerLevel.addEntity(MixinServerLevel.java) ~[?:?]
        at knot/net.minecraft.server.level.ServerLevel.addFreshEntity(MixinServerLevel.java:893) ~[?:?]
        at knot/com.notunanancyowen.goals.VillagerSpecificRoleGoal.tick(VillagerSpecificRoleGoal.java:85) ~[mob-ai-tweaks-1.3.6-1.21.jar:?]
        at knot/net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:65) ~[?:?]
        at knot/net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:112) ~[?:?]
        at knot/net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:103) ~[?:?]
        at knot/net.minecraft.world.entity.Mob.serverAiStep(Mob.java:794) ~[?:?]
        at knot/net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:2778) ~[?:?]
        at knot/net.minecraft.world.entity.Mob.aiStep(Mob.java:572) ~[?:?]
        at knot/net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:128) ~[?:?]
        at knot/net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2507) ~[?:?]
        at knot/net.minecraft.world.entity.Mob.tick(Mob.java:372) ~[?:?]
        at knot/net.minecraft.world.entity.npc.Villager.tick(Villager.java:320) ~[?:?]
        at knot/net.minecraft.server.level.ServerLevel.mixinextras$bridge$method_5773$310(MixinServerLevel.java) ~[?:?]
        at knot/net.minecraft.server.level.ServerLevel.wrapOperation$gle001$porting_lib_entity$preEntityTick(MixinServerLevel.java:21307) ~[?:?]
        at knot/net.minecraft.server.level.ServerLevel.tickNonPassenger(MixinServerLevel.java:770) ~[?:?]
        at knot/com.axalotl.async.ParallelProcessor.performAsyncEntityTick(ParallelProcessor.java:123) ~[async-0.1.2+alpha.1-1.21.1.jar:?]
        at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$4(ParallelProcessor.java:82) ~[async-0.1.2+alpha.1-1.21.1.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```
