### ISSUE TITLE
Client crashes after new update in 1.20.1

### ISSUE THREAD

**Issue by Fukuyarieru** [Unknowneth/Mob-AI-Tweaks#22]
Just a client crash, happens since the update (2 hours ago), Client works without the mod.
Here is the crash report:

> ---- Minecraft Crash Report ----
> // There are four lights!
> 
> Time: 2024-12-07 15:04:33
> Description: Initializing game
> 
> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mob-ai-tweaks' at 'com.notunanancyowen.MobAITweaks'!
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
> 	at knot//fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
> 	at knot//net.minecraft.class_310.redirect$dke000$notenoughcrashes$catchFabricInit(class_310.java:21011)
> 	at knot//net.minecraft.class_310.<init>(class_310.java:458)
> 	at knot//net.minecraft.client.main.Main.main(Main.java:211)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> Caused by: java.lang.RuntimeException: Attempted to register ID ResourceKey[minecraft:enchantment / mob-ai-tweaks:after_burner] at different raw IDs (61, 68)! If you're trying to override an item, use .set(), not .register()!
> 	at knot//net.minecraft.class_2370.handler$cfd000$fabric-registry-sync-v0$setPre(class_2370.java:705)
> 	at knot//net.minecraft.class_2370.method_46744(class_2370.java)
> 	at knot//net.minecraft.class_2370.method_10272(class_2370.java:186)
> 	at knot//net.minecraft.class_2378.method_39197(class_2378.java:118)
> 	at knot//net.minecraft.class_2378.method_10230(class_2378.java:114)
> 	at knot//com.notunanancyowen.MobAITweaks.lambda$onInitialize$1(MobAITweaks.java:158)
> 	at java.base/java.lang.StringLatin1$LinesSpliterator.forEachRemaining(Unknown Source)
> 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
> 	at knot//com.notunanancyowen.MobAITweaks.onInitialize(MobAITweaks.java:154)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
> 	... 8 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
> 	at knot//fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
> 	at knot//net.minecraft.class_310.redirect$dke000$notenoughcrashes$catchFabricInit(class_310.java:21011)
> 	at knot//net.minecraft.class_310.<init>(class_310.java:458)
> 
> -- Initialization --
> Details:
> 	...<80 Lines of Microsoft stuff>
> Stacktrace:
> 	at knot//net.minecraft.client.main.Main.main(Main.java:211)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
>

**Comment by Unknowneth** [comment]
ok, gimme a few hours

**Comment by Unknowneth** [comment]
btw, try restarting your client, I am not encountering this crash at all, could just be the game not updating its config properly or the server host did not update their mods (if you're ever playing on lan)

alternatively, set "enchantments_from_mod" to false in the config in case the host disabled them

**Comment by Unknowneth** [comment]
should hopefully be fixed as of 1.5.1 for 1.20, close the issue if it actually is fixed for your case (if not, try the solutions I put above)
