### ISSUE TITLE
mixin breakage in 1.20.1 forge v1.3.0

### ISSUE THREAD

**Issue by Mysticpasta1** [Unknowneth/Mob-AI-Tweaks#3]
Re did my issue due to a malware bot
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method fixBowUseBug(Lnet/minecraft/world/InteractionHand;)Lnet/minecraft/world/InteractionHand; in mob-ai-tweaks.mixins.json:RangedBowAttackGoalMixin from mod mob_ai_tweaks failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mob-ai-tweaks-refmap.json

**Comment by Unknowneth** [comment]
what do you use to show mixin errors on forge? Mine doesn't tell me jack shit making this annoyingly hard to fix

**Comment by Mysticpasta1** [comment]
I use intellij community edition

**Comment by Mysticpasta1** [comment]
my discord is HauntedPasta1

**Comment by Mysticpasta1** [comment]
I told you I would help you I have discord :D

**Comment by Mysticpasta1** [comment]
I'm going to fix everything in a PR

**Comment by Mysticpasta1** [comment]
I'm going to fix everything in a PR

**Comment by Mysticpasta1** [comment]
@Unknowneth I can help you do you have Discord,

the latest build on forge + connector has this issue

**Comment by Mysticpasta1** [comment]
it says it is on fabric (1.3.2)

**Comment by Mysticpasta1** [comment]
```23:23:23.420
game
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
23:23:23.420
game
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
23:23:23.420
game
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
23:23:23.420
game
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
23:23:23.420
game
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
23:23:23.420
game
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.EntityType.<clinit>(EntityType.java:219)
23:23:23.420
game
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.Items.<clinit>(Items.java:754)
23:23:23.420
game
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.ComposterBlock.m_51988_(ComposterBlock.java:60)
23:23:23.420
game
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:47)
23:23:23.420
game
at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.lambda$main$0(Main.java:151)
23:23:23.420
game
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
23:23:23.420
game
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
23:23:23.420
game
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
23:23:23.420
game
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
23:23:23.420
game
at java.base/java.lang.Thread.run(Thread.java:833)
23:23:23.420
game
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method fixBowUseBug(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in mob-ai-tweaks.mixins.json:RangedBowAttackGoalMixin from mod mob_ai_tweaks failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mob-ai-tweaks-refmap.json
23:23:23.420
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
23:23:23.420
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
23:23:23.420
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
23:23:23.420
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
23:23:23.420
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
23:23:23.420
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
23:23:23.420
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
23:23:23.420
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
23:23:23.420
game
... 23 more```

**Comment by Mysticpasta1** [comment]
https://gist.github.com/Mysticpasta1/6e9a9f35588c048f87bb224695101f62

**Comment by Mysticpasta1** [comment]
here is the full error
